//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.DBEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Car
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Car()
        {
            this.Orders = new HashSet<Order>();
        }
    
        public int CarID { get; set; }
        public int RowID { get; set; }
        public int CustomerID { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public string VinNo { get; set; }
        public Nullable<int> MakeID { get; set; }
        public Nullable<int> ModelID { get; set; }
        public Nullable<int> Year { get; set; }
        public string Color { get; set; }
        public string RegistrationNo { get; set; }
        public Nullable<double> CheckLitre { get; set; }
        public string EngineType { get; set; }
        public string RecommendedAmount { get; set; }
        public Nullable<int> StatusID { get; set; }
        public string BinaryImage { get; set; }
        public string LastUpdatedBy { get; set; }
        public string LastUpdatedDate { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<int> LocationID { get; set; }
        public int UserID { get; set; }
        public string ImagePath { get; set; }
        public string Gender { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual Make Make { get; set; }
        public virtual Model Model { get; set; }
        public virtual User User { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Order> Orders { get; set; }
    }
}
