//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.DBEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class CarInspectionMapping
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CarInspectionMapping()
        {
            this.CarInspectionMapping1 = new HashSet<CarInspectionMapping>();
        }
    
        public int InspectionMappingID { get; set; }
        public int RowID { get; set; }
        public int OrderID { get; set; }
        public string Name { get; set; }
        public string AlternateName { get; set; }
        public string Image { get; set; }
        public string Description { get; set; }
        public Nullable<int> SubInspectionID { get; set; }
        public Nullable<int> StatusID { get; set; }
        public int LocationID { get; set; }
        public Nullable<bool> IsInspection { get; set; }
        public Nullable<bool> IsReplace { get; set; }
        public Nullable<bool> IsInspectWithoutReplace { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CarInspectionMapping> CarInspectionMapping1 { get; set; }
        public virtual CarInspectionMapping CarInspectionMapping2 { get; set; }
        public virtual Location Location { get; set; }
        public virtual Order Order { get; set; }
    }
}
