//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.DBEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class CarNote
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CarNote()
        {
            this.CarNotesImages = new HashSet<CarNotesImage>();
        }
    
        public int CarNotesID { get; set; }
        public int RowID { get; set; }
        public string NotesComment { get; set; }
        public string NotesStatus { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<int> StatusID { get; set; }
        public Nullable<int> CarID { get; set; }
        public int OrderID { get; set; }
        public int LocaitonID { get; set; }
        public string LastUpdatedBy { get; set; }
        public Nullable<System.DateTime> LastUpdatedDate { get; set; }
    
        public virtual Location Location { get; set; }
        public virtual Order Order { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CarNotesImage> CarNotesImages { get; set; }
    }
}
