//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.DBEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class inv_StockRequestDetail
    {
        public int StockRequestDetailID { get; set; }
        public Nullable<int> StockRequestID { get; set; }
        public Nullable<int> ItemID { get; set; }
        public Nullable<int> Qty { get; set; }
        public Nullable<int> IssueQty { get; set; }
        public Nullable<int> UnitID { get; set; }
        public string Remarks { get; set; }
        public Nullable<int> StatusID { get; set; }
        public Nullable<System.DateTime> LastUpdateDate { get; set; }
        public string LastUpdatedBy { get; set; }
    
        public virtual inv_StockRequest inv_StockRequest { get; set; }
        public virtual Item Item { get; set; }
        public virtual Unit Unit { get; set; }
    }
}
