//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.DBEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class inv_StockStore
    {
        public int StockStoreID { get; set; }
        public Nullable<int> InventoryID { get; set; }
        public Nullable<int> StoreID { get; set; }
        public Nullable<int> MinimumStock { get; set; }
        public Nullable<int> CurrentStock { get; set; }
        public Nullable<int> StatusID { get; set; }
        public string LastUpdatedBy { get; set; }
        public Nullable<System.DateTime> LastUpdatedDate { get; set; }
        public Nullable<int> OpeningStock { get; set; }
        public Nullable<int> StockSold { get; set; }
        public Nullable<int> UserID { get; set; }
    
        public virtual Inventory Inventory { get; set; }
        public virtual Store Store { get; set; }
        public virtual User User { get; set; }
    }
}
