//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.DBEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class inv_BillDetail
    {
        public int BillDetailID { get; set; }
        public Nullable<int> BillID { get; set; }
        public int ItemID { get; set; }
        public Nullable<double> Cost { get; set; }
        public Nullable<double> Price { get; set; }
        public Nullable<int> Quantity { get; set; }
        public Nullable<double> Total { get; set; }
        public Nullable<int> StatusID { get; set; }
        public string Remarks { get; set; }
        public Nullable<System.DateTime> LastUpdatedDate { get; set; }
        public string LastUpdatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public string CreatedBy { get; set; }
    
        public virtual inv_Bill inv_Bill { get; set; }
        public virtual Item Item { get; set; }
    }
}
