//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.DBEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class inv_Stock
    {
        public int StockID { get; set; }
        public string PurhaseOrderNo { get; set; }
        public string BillNo { get; set; }
        public Nullable<int> StockIn { get; set; }
        public Nullable<int> StockOut { get; set; }
        public Nullable<int> CurrentStock { get; set; }
        public Nullable<int> ItemID { get; set; }
        public string Type { get; set; }
        public string Remarks { get; set; }
        public Nullable<int> StatusID { get; set; }
        public Nullable<System.DateTime> LastUpdatedDate { get; set; }
        public string LastUpdatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public string CreatedBy { get; set; }
        public int StoreID { get; set; }
        public int UserID { get; set; }
    
        public virtual Store Store { get; set; }
        public virtual User User { get; set; }
        public virtual Item Item { get; set; }
    }
}
