//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.DBEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderCheckout
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public OrderCheckout()
        {
            this.OrderCheckoutDetails = new HashSet<OrderCheckoutDetail>();
        }
    
        public int OrderCheckOutID { get; set; }
        public int OrderID { get; set; }
        public string SessionId { get; set; }
        public string CheckoutDate { get; set; }
        public Nullable<double> AmountTotal { get; set; }
        public Nullable<int> OrderStatus { get; set; }
        public Nullable<double> AmountPaid { get; set; }
        public Nullable<double> AmountDiscount { get; set; }
        public Nullable<double> RefundedAmount { get; set; }
        public Nullable<double> Tax { get; set; }
        public Nullable<double> GrandTotal { get; set; }
        public string lastUpdateBy { get; set; }
        public Nullable<System.DateTime> LastUpdateDT { get; set; }
        public Nullable<int> Gratuity { get; set; }
        public Nullable<double> ServiceCharges { get; set; }
        public string Remarks { get; set; }
        public int LocationID { get; set; }
        public Nullable<bool> IsPaid { get; set; }
        public Nullable<double> AmountComplementary { get; set; }
        public Nullable<bool> IsReady { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<int> WorkerID { get; set; }
        public Nullable<int> AssistantID { get; set; }
        public Nullable<int> PaymentMode { get; set; }
        public Nullable<int> SubUserID { get; set; }
    
        public virtual Location Location { get; set; }
        public virtual Order Order { get; set; }
        public virtual SubUser SubUser { get; set; }
        public virtual SubUser SubUser1 { get; set; }
        public virtual SubUser SubUser2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderCheckoutDetail> OrderCheckoutDetails { get; set; }
    }
}
