//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.DBEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrdersChecklist
    {
        public int OrderChecklistID { get; set; }
        public int OrderID { get; set; }
        public Nullable<int> InspectionDetailID { get; set; }
        public Nullable<int> SubOrderChecklistID { get; set; }
        public string Name { get; set; }
        public string AlternateName { get; set; }
        public string Value { get; set; }
        public string KM { get; set; }
        public Nullable<int> StatusID { get; set; }
        public Nullable<int> LocationID { get; set; }
        public string LastUpdatedBy { get; set; }
        public Nullable<System.DateTime> LastUpdatedDate { get; set; }
    
        public virtual Order Order { get; set; }
    }
}
